#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config/.kodi/userdata \
	/var/cache/samba

# copy config
[[ ! -e /config/.kodi/userdata/advancedsettings.xml ]] && \
	cp /defaults/advancedsettings.xml /config/.kodi/userdata/advancedsettings.xml
	
	
#make cron job for auto updates
[[ ! -e /mnt/con.conf ]] && \
	cp /config/.kodi/cron.conf /mnt/cron.conf
	cp /config/update.sh /mnt/update.sh
	cp /config/clean.sh /mnt/clean.sh
chmod 600 /mnt/cron.conf
chmod +x /mnt/clean.sh
chmod +x /mnt/update.sh
crontab /mnt/cron.conf

# permissions
chown -R abc:abc \
	/config \
	/var/cache/samba
